# Generated by Django 3.1.5 on 2021-01-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='time_without_charge',
            field=models.SmallIntegerField(default=0, help_text='Укажите время в часах', verbose_name='Вребя работы аккумулятора'),
        ),
    ]
