# Generated by Django 3.1.5 on 2021-01-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210123_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fro_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
